language: java
notifications:
  slack: mishima-group:8zsPeLEBTdLyT7kCZdQzIx4c
deploy:
  provider: heroku
  api-key:
    secure: PCWz2UmKSTuwpJK+loGg6aSr1OsFET+g0pFFyUdtcsCt9LXWA0VlASdNkiEXN1JjRWOb7k69cSKYteAbScWEPxnfWwy/Ne5zK+l/msKqSsQZgwaBDoFEufhNuwLnClqRAZkjthz9ZgynQsSnkw93LR1eeudGYpKegv5TG2QGWiXbfF+cSNGYWJQub8EnPaBMt7T5pzm/FNwXFwOz8kVIlHTJhRoMm9YSbfjF/3ZwJd8WJQDX3qaiQG38OCcltDhptBbx6i+TiAI9V7Ulv9h5XV16OEMyBByBvqHzz6bcPh1pxhYwToUN1NNZSrqG3YiN7XjZk+CH0dxJZcmeiRJAJ3d54c4YbTFThdWPOkHlDPF3PfgbkuZBRIf2FJdXM85RGOrycMsK5ulA2+/jQZPd5GL9Re8+ssp2ZGzqqtMEP8WOlnpQ78zEW++vMtTDv++HoOtJxmsn5ZP9VlpDlCaVmecSStZmKoCfVid1Q4Y/h/+Chfec8n1RMrHTaJLPCNJwMCV2dpEwafR5mQv9itucmyGlGEWifBnCsAPkaDMRMV/Bu558MuYId/arGkowjfz126/viaG3VBvyJ859+xiegRS1RE/aIQt/C1TRui2f9nKxqyCjKQ00KkchkFmSCRfICRAujOlLKtM6l7XEOWmykNJgwNVlwHNzKH99E2AEEAU=
